export { FindNamesRequest } from './FindNamesRequest'
export { GetPokemonRequest } from './GetPokemonRequest'
export { GetPokemonByNoRequest } from './GetPokemonByNoRequest'
export { GetStatsRequest } from './GetStatsRequest'
export { CalcDamageRequest } from './CalcDamageRequest'
